name: 🌟 Frontend CI/CD

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "frontend/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Run Tests
        run: cd frontend && npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Frontend
        run: echo "Deploying frontend..."
