name: Deployment Backend Staging

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Go Production build
        run: |
          cd ./backend
          env GOOS=linux GOARCH=amd64 go build -o ./backend-file-build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build-artifact
          path: |
            ./backend/backend-file-build
            ./backend/config.yml
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install Necessary Go Libraries
        run: |
          cd ./backend
          go install github.com/vektra/mockery/v2@v2.50.0
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
          go install github.com/boumenot/gocover-cobertura@latest
      - name: Generate mock interface
        run: |
          cd ./backend
          touch config.yml
          echo '${{secrets.BACKEND_STAGING_ENV}}' > config.yml
          go mod tidy
          mockery --all --with-expecter --dir=./internals/repositories --output=./mocks/repositories --outpkg=mockRepositories 
          mockery --all --with-expecter --dir=./internals/services --output=./mocks/services --outpkg=mockServices 
          mockery --all --with-expecter --dir=./internals/utils/services --output=./mocks/utils --outpkg=mockUtilServices

      - name: Test Services & Controllers
        run: |
          cd ./backend
          go test -race -json -v -coverprofile=coverage.txt ./internals/controllers/ ./internals/services/ 2>&1 | tee /tmp/gotest.log | gotestfmt
          gocover-cobertura < coverage.txt > coverage.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: |
            ./backend/coverage.txt
            ./backend/coverage.xml
      - name: Check Code Coverage
        run: |
          cd ./backend
          coverage=$(go tool cover -func=coverage.txt | grep total | awk '{print $3}' | sed 's/%//')
          echo "Code Coverage: $coverage%"
          if (( $(echo "$coverage < 80" | bc -l) )); then
            echo "Code coverage is below 80%. Failing the job."
            exit 1
          fi

  code_coverage:
    name: "code coverage report"
    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
    runs-on: ubuntu-latest
    needs: [backend-test] # Depends on the artifact uploaded by the "unit_tests" job
    permissions:
      contents: read
      actions: read # to download code coverage results from "test" job
      pull-requests: write # write permission needed to comment on PR
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: .

      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  deploy:
    runs-on: ubuntu-latest
    needs: [backend-build, backend-test]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Stop Current Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: pm2 stop 5

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{secrets.SSH_USERNAME}}
          server: ${{secrets.SSH_HOST}}
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          local_path: "./backend-build-artifact/*"
          remote_path: "/root/backend/staging/"

      - name: Start Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: pm2 start 5
